### PR TITLE
Rewrite for scalability

### PR DESCRIPTION
**Pull request by cjmarkham**

### CODE REVIEW

**Comment by scottrobertson** [comment]
Hey,

Looks good. Only thing is, how did you manage to get merge conflicts when compared to master? Did you not pull the latest code before making changes? Merge master of my remote into your remote and see if there are conflicts.

**Comment by ghost** [comment]
Did pull, only thing I can think is because it was a complete rewrite. Will merge master tonight.

**Comment by scottrobertson** [comment]
Even if it was a complete rewrite it would not cause a merge conflict unless you started from a point behind master.

**Comment by scottrobertson** [comment]
Merged and pushed to http://scottrobertson.github.io/installer/

**Pull request merged**
